/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QWidget *widget_RTClient;
    QLabel *label_RTClient;
    QPushButton *pBtn_ConnectUR;
    QLineEdit *lineEdt_IPAdress;
    QPushButton *pBtn_DisconnectUR;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QFrame *line_6;
    QWidget *widget_DashBoard;
    QPushButton *pBtn_Powerdown;
    QPushButton *pBtn_BreakRelease;
    QPushButton *pBtn_Poweron;
    QPushButton *pBtn_Poweroff;
    QLabel *label_DashBoard;
    QFrame *line_7;
    QWidget *widget;
    QPushButton *pBtn_StopJoint;
    QPushButton *pBtn_BackStart;
    QPushButton *pBtn_BackZero;
    QFrame *line_8;
    QFrame *line_9;
    QFrame *line_10;
    QToolButton *tBtn_TCPZDirDec;
    QLabel *label_TCPDirection;
    QLabel *label_TCPPostion;
    QToolButton *tBtn_TCPZDirAdd;
    QToolButton *tBtn_TCPYDirAdd;
    QToolButton *tBtn_TCPYDirDec;
    QToolButton *tBtn_TCPXDirDec;
    QToolButton *tBtn_TCPXDirAdd;
    QToolButton *tBtn_TCPXPosAdd;
    QToolButton *tBtn_TCPZPosAdd;
    QToolButton *tBtn_TCPYPosAdd;
    QToolButton *tBtn_TCPXPosDec;
    QToolButton *tBtn_TCPZPosDec;
    QToolButton *tBtn_TCPYPosDec;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QSlider *Slider_Base;
    QTabWidget *tabWidget;
    QWidget *tab_current;
    QLineEdit *lineEdit_X;
    QLineEdit *lineEdit_Y;
    QLineEdit *lineEdit_RX;
    QLineEdit *lineEdit_Z;
    QLineEdit *lineEdit_RZ;
    QLineEdit *lineEdit_RY;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QWidget *tab_target;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *lineEdit_Z_target;
    QLabel *label_34;
    QLineEdit *lineEdit_Y_target;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *lineEdit_X_target;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLineEdit *lineEdit_RZ_target;
    QLineEdit *lineEdit_RX_target;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLineEdit *lineEdit_RY_target;
    QToolButton *tBtn_URBaseDec;
    QToolButton *tBtn_URBaseAdd;
    QLineEdit *lineEdit_base;
    QLabel *label_base;
    QToolButton *tBtn_URShoulderAdd;
    QLineEdit *lineEdit_shoulder;
    QLabel *label_shoulder;
    QSlider *Slider_Shoulder;
    QToolButton *tBtn_URShoulderDec;
    QToolButton *tBtn_URElbowAdd;
    QLineEdit *lineEdit_elbow;
    QLabel *label_elbow;
    QSlider *Slider_Elbow;
    QToolButton *tBtn_URElbowDec;
    QToolButton *tBtn_URWrist1Add;
    QToolButton *tBtn_URWrist2Add;
    QSlider *Slider_Wrist2;
    QToolButton *tBtn_URWrist3Add;
    QToolButton *tBtn_URWrist3Dec;
    QLabel *label_wrist3;
    QLineEdit *lineEdit_wrist1;
    QLabel *label_wrist2;
    QToolButton *tBtn_URWrist2Dec;
    QLineEdit *lineEdit_wrist3;
    QLabel *label_wrist1;
    QLineEdit *lineEdit_wrist2;
    QSlider *Slider_Wrist1;
    QToolButton *tBtn_URWrist1Dec;
    QSlider *Slider_Wrist3;
    QLabel *label_TCPDirection_2;
    QLabel *label_TCPDirection_3;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QPushButton *pBtn_MoveTo;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1278, 725);
        QFont font;
        font.setFamily(QString::fromUtf8("PingFang SC"));
        font.setPointSize(10);
        font.setBold(false);
        font.setItalic(false);
        font.setWeight(50);
        font.setStyleStrategy(QFont::PreferAntialias);
        MainWindow->setFont(font);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        widget_RTClient = new QWidget(centralwidget);
        widget_RTClient->setObjectName(QString::fromUtf8("widget_RTClient"));
        widget_RTClient->setGeometry(QRect(20, 10, 361, 121));
        label_RTClient = new QLabel(widget_RTClient);
        label_RTClient->setObjectName(QString::fromUtf8("label_RTClient"));
        label_RTClient->setGeometry(QRect(30, 50, 78, 24));
        label_RTClient->setFont(font);
        label_RTClient->setLineWidth(1);
        label_RTClient->setAlignment(Qt::AlignCenter);
        pBtn_ConnectUR = new QPushButton(widget_RTClient);
        pBtn_ConnectUR->setObjectName(QString::fromUtf8("pBtn_ConnectUR"));
        pBtn_ConnectUR->setGeometry(QRect(130, 70, 100, 33));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(pBtn_ConnectUR->sizePolicy().hasHeightForWidth());
        pBtn_ConnectUR->setSizePolicy(sizePolicy);
        pBtn_ConnectUR->setFont(font);
        lineEdt_IPAdress = new QLineEdit(widget_RTClient);
        lineEdt_IPAdress->setObjectName(QString::fromUtf8("lineEdt_IPAdress"));
        lineEdt_IPAdress->setGeometry(QRect(130, 20, 211, 30));
        sizePolicy.setHeightForWidth(lineEdt_IPAdress->sizePolicy().hasHeightForWidth());
        lineEdt_IPAdress->setSizePolicy(sizePolicy);
        QFont font1;
        font1.setFamily(QString::fromUtf8("PingFang SC"));
        font1.setPointSize(10);
        font1.setBold(false);
        font1.setItalic(false);
        font1.setWeight(50);
        lineEdt_IPAdress->setFont(font1);
        lineEdt_IPAdress->setAlignment(Qt::AlignCenter);
        pBtn_DisconnectUR = new QPushButton(widget_RTClient);
        pBtn_DisconnectUR->setObjectName(QString::fromUtf8("pBtn_DisconnectUR"));
        pBtn_DisconnectUR->setGeometry(QRect(240, 70, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_DisconnectUR->sizePolicy().hasHeightForWidth());
        pBtn_DisconnectUR->setSizePolicy(sizePolicy);
        pBtn_DisconnectUR->setFont(font);
        line = new QFrame(centralwidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(10, 10, 20, 691));
        sizePolicy.setHeightForWidth(line->sizePolicy().hasHeightForWidth());
        line->setSizePolicy(sizePolicy);
        line->setFrameShadow(QFrame::Plain);
        line->setLineWidth(3);
        line->setFrameShape(QFrame::VLine);
        line_2 = new QFrame(centralwidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(20, 670, 1241, 61));
        sizePolicy.setHeightForWidth(line_2->sizePolicy().hasHeightForWidth());
        line_2->setSizePolicy(sizePolicy);
        line_2->setFrameShadow(QFrame::Plain);
        line_2->setLineWidth(3);
        line_2->setFrameShape(QFrame::HLine);
        line_3 = new QFrame(centralwidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(1250, 10, 20, 691));
        sizePolicy.setHeightForWidth(line_3->sizePolicy().hasHeightForWidth());
        line_3->setSizePolicy(sizePolicy);
        line_3->setFrameShadow(QFrame::Plain);
        line_3->setLineWidth(3);
        line_3->setFrameShape(QFrame::VLine);
        line_4 = new QFrame(centralwidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(20, -20, 1241, 61));
        sizePolicy.setHeightForWidth(line_4->sizePolicy().hasHeightForWidth());
        line_4->setSizePolicy(sizePolicy);
        line_4->setFrameShadow(QFrame::Plain);
        line_4->setLineWidth(3);
        line_4->setFrameShape(QFrame::HLine);
        line_5 = new QFrame(centralwidget);
        line_5->setObjectName(QString::fromUtf8("line_5"));
        line_5->setGeometry(QRect(373, 10, 20, 691));
        sizePolicy.setHeightForWidth(line_5->sizePolicy().hasHeightForWidth());
        line_5->setSizePolicy(sizePolicy);
        line_5->setFrameShape(QFrame::VLine);
        line_5->setFrameShadow(QFrame::Sunken);
        line_6 = new QFrame(centralwidget);
        line_6->setObjectName(QString::fromUtf8("line_6"));
        line_6->setGeometry(QRect(20, 130, 361, 16));
        sizePolicy.setHeightForWidth(line_6->sizePolicy().hasHeightForWidth());
        line_6->setSizePolicy(sizePolicy);
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        widget_DashBoard = new QWidget(centralwidget);
        widget_DashBoard->setObjectName(QString::fromUtf8("widget_DashBoard"));
        widget_DashBoard->setGeometry(QRect(20, 140, 361, 121));
        pBtn_Powerdown = new QPushButton(widget_DashBoard);
        pBtn_Powerdown->setObjectName(QString::fromUtf8("pBtn_Powerdown"));
        pBtn_Powerdown->setGeometry(QRect(130, 10, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_Powerdown->sizePolicy().hasHeightForWidth());
        pBtn_Powerdown->setSizePolicy(sizePolicy);
        pBtn_Powerdown->setFont(font);
        pBtn_BreakRelease = new QPushButton(widget_DashBoard);
        pBtn_BreakRelease->setObjectName(QString::fromUtf8("pBtn_BreakRelease"));
        pBtn_BreakRelease->setGeometry(QRect(240, 10, 100, 33));
        QSizePolicy sizePolicy1(QSizePolicy::Preferred, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(pBtn_BreakRelease->sizePolicy().hasHeightForWidth());
        pBtn_BreakRelease->setSizePolicy(sizePolicy1);
        pBtn_BreakRelease->setFont(font);
        pBtn_Poweron = new QPushButton(widget_DashBoard);
        pBtn_Poweron->setObjectName(QString::fromUtf8("pBtn_Poweron"));
        pBtn_Poweron->setGeometry(QRect(130, 70, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_Poweron->sizePolicy().hasHeightForWidth());
        pBtn_Poweron->setSizePolicy(sizePolicy);
        pBtn_Poweron->setFont(font);
        pBtn_Poweroff = new QPushButton(widget_DashBoard);
        pBtn_Poweroff->setObjectName(QString::fromUtf8("pBtn_Poweroff"));
        pBtn_Poweroff->setGeometry(QRect(240, 70, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_Poweroff->sizePolicy().hasHeightForWidth());
        pBtn_Poweroff->setSizePolicy(sizePolicy);
        pBtn_Poweroff->setFont(font);
        label_DashBoard = new QLabel(widget_DashBoard);
        label_DashBoard->setObjectName(QString::fromUtf8("label_DashBoard"));
        label_DashBoard->setGeometry(QRect(20, 50, 101, 24));
        label_DashBoard->setFont(font);
        label_DashBoard->setLineWidth(1);
        label_DashBoard->setAlignment(Qt::AlignCenter);
        line_7 = new QFrame(centralwidget);
        line_7->setObjectName(QString::fromUtf8("line_7"));
        line_7->setGeometry(QRect(20, 260, 361, 16));
        sizePolicy.setHeightForWidth(line_7->sizePolicy().hasHeightForWidth());
        line_7->setSizePolicy(sizePolicy);
        line_7->setFrameShape(QFrame::HLine);
        line_7->setFrameShadow(QFrame::Sunken);
        widget = new QWidget(centralwidget);
        widget->setObjectName(QString::fromUtf8("widget"));
        widget->setGeometry(QRect(20, 270, 361, 71));
        pBtn_StopJoint = new QPushButton(widget);
        pBtn_StopJoint->setObjectName(QString::fromUtf8("pBtn_StopJoint"));
        pBtn_StopJoint->setGeometry(QRect(20, 20, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_StopJoint->sizePolicy().hasHeightForWidth());
        pBtn_StopJoint->setSizePolicy(sizePolicy);
        pBtn_StopJoint->setFont(font);
        pBtn_BackStart = new QPushButton(widget);
        pBtn_BackStart->setObjectName(QString::fromUtf8("pBtn_BackStart"));
        pBtn_BackStart->setGeometry(QRect(130, 20, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_BackStart->sizePolicy().hasHeightForWidth());
        pBtn_BackStart->setSizePolicy(sizePolicy);
        pBtn_BackStart->setFont(font);
        pBtn_BackZero = new QPushButton(widget);
        pBtn_BackZero->setObjectName(QString::fromUtf8("pBtn_BackZero"));
        pBtn_BackZero->setGeometry(QRect(240, 20, 100, 33));
        sizePolicy.setHeightForWidth(pBtn_BackZero->sizePolicy().hasHeightForWidth());
        pBtn_BackZero->setSizePolicy(sizePolicy);
        pBtn_BackZero->setFont(font);
        line_8 = new QFrame(widget);
        line_8->setObjectName(QString::fromUtf8("line_8"));
        line_8->setGeometry(QRect(0, 60, 361, 16));
        sizePolicy.setHeightForWidth(line_8->sizePolicy().hasHeightForWidth());
        line_8->setSizePolicy(sizePolicy);
        line_8->setFrameShape(QFrame::HLine);
        line_8->setFrameShadow(QFrame::Sunken);
        line_9 = new QFrame(centralwidget);
        line_9->setObjectName(QString::fromUtf8("line_9"));
        line_9->setGeometry(QRect(380, 330, 881, 16));
        sizePolicy.setHeightForWidth(line_9->sizePolicy().hasHeightForWidth());
        line_9->setSizePolicy(sizePolicy);
        line_9->setFrameShape(QFrame::HLine);
        line_9->setFrameShadow(QFrame::Sunken);
        line_10 = new QFrame(centralwidget);
        line_10->setObjectName(QString::fromUtf8("line_10"));
        line_10->setGeometry(QRect(790, 10, 20, 321));
        sizePolicy.setHeightForWidth(line_10->sizePolicy().hasHeightForWidth());
        line_10->setSizePolicy(sizePolicy);
        line_10->setFrameShape(QFrame::VLine);
        line_10->setFrameShadow(QFrame::Sunken);
        tBtn_TCPZDirDec = new QToolButton(centralwidget);
        tBtn_TCPZDirDec->setObjectName(QString::fromUtf8("tBtn_TCPZDirDec"));
        tBtn_TCPZDirDec->setGeometry(QRect(480, 80, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPZDirDec->sizePolicy().hasHeightForWidth());
        tBtn_TCPZDirDec->setSizePolicy(sizePolicy);
        tBtn_TCPZDirDec->setCheckable(false);
        tBtn_TCPZDirDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPZDirDec->setAutoRaise(false);
        tBtn_TCPZDirDec->setArrowType(Qt::DownArrow);
        label_TCPDirection = new QLabel(centralwidget);
        label_TCPDirection->setObjectName(QString::fromUtf8("label_TCPDirection"));
        label_TCPDirection->setGeometry(QRect(410, 30, 111, 24));
        label_TCPDirection->setFont(font);
        label_TCPPostion = new QLabel(centralwidget);
        label_TCPPostion->setObjectName(QString::fromUtf8("label_TCPPostion"));
        label_TCPPostion->setGeometry(QRect(830, 30, 111, 24));
        label_TCPPostion->setFont(font);
        tBtn_TCPZDirAdd = new QToolButton(centralwidget);
        tBtn_TCPZDirAdd->setObjectName(QString::fromUtf8("tBtn_TCPZDirAdd"));
        tBtn_TCPZDirAdd->setGeometry(QRect(620, 80, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPZDirAdd->sizePolicy().hasHeightForWidth());
        tBtn_TCPZDirAdd->setSizePolicy(sizePolicy);
        tBtn_TCPZDirAdd->setCheckable(false);
        tBtn_TCPZDirAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPZDirAdd->setAutoRaise(false);
        tBtn_TCPZDirAdd->setArrowType(Qt::UpArrow);
        tBtn_TCPYDirAdd = new QToolButton(centralwidget);
        tBtn_TCPYDirAdd->setObjectName(QString::fromUtf8("tBtn_TCPYDirAdd"));
        tBtn_TCPYDirAdd->setGeometry(QRect(570, 140, 51, 71));
        sizePolicy.setHeightForWidth(tBtn_TCPYDirAdd->sizePolicy().hasHeightForWidth());
        tBtn_TCPYDirAdd->setSizePolicy(sizePolicy);
        tBtn_TCPYDirAdd->setCheckable(false);
        tBtn_TCPYDirAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPYDirAdd->setAutoRaise(false);
        tBtn_TCPYDirAdd->setArrowType(Qt::UpArrow);
        tBtn_TCPYDirDec = new QToolButton(centralwidget);
        tBtn_TCPYDirDec->setObjectName(QString::fromUtf8("tBtn_TCPYDirDec"));
        tBtn_TCPYDirDec->setGeometry(QRect(570, 240, 51, 71));
        sizePolicy.setHeightForWidth(tBtn_TCPYDirDec->sizePolicy().hasHeightForWidth());
        tBtn_TCPYDirDec->setSizePolicy(sizePolicy);
        tBtn_TCPYDirDec->setCheckable(false);
        tBtn_TCPYDirDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPYDirDec->setAutoRaise(false);
        tBtn_TCPYDirDec->setArrowType(Qt::DownArrow);
        tBtn_TCPXDirDec = new QToolButton(centralwidget);
        tBtn_TCPXDirDec->setObjectName(QString::fromUtf8("tBtn_TCPXDirDec"));
        tBtn_TCPXDirDec->setGeometry(QRect(440, 200, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPXDirDec->sizePolicy().hasHeightForWidth());
        tBtn_TCPXDirDec->setSizePolicy(sizePolicy);
        tBtn_TCPXDirDec->setCheckable(false);
        tBtn_TCPXDirDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPXDirDec->setAutoRaise(false);
        tBtn_TCPXDirDec->setArrowType(Qt::LeftArrow);
        tBtn_TCPXDirAdd = new QToolButton(centralwidget);
        tBtn_TCPXDirAdd->setObjectName(QString::fromUtf8("tBtn_TCPXDirAdd"));
        tBtn_TCPXDirAdd->setGeometry(QRect(650, 200, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPXDirAdd->sizePolicy().hasHeightForWidth());
        tBtn_TCPXDirAdd->setSizePolicy(sizePolicy);
        tBtn_TCPXDirAdd->setCheckable(false);
        tBtn_TCPXDirAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPXDirAdd->setAutoRaise(false);
        tBtn_TCPXDirAdd->setArrowType(Qt::RightArrow);
        tBtn_TCPXPosAdd = new QToolButton(centralwidget);
        tBtn_TCPXPosAdd->setObjectName(QString::fromUtf8("tBtn_TCPXPosAdd"));
        tBtn_TCPXPosAdd->setGeometry(QRect(1090, 200, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPXPosAdd->sizePolicy().hasHeightForWidth());
        tBtn_TCPXPosAdd->setSizePolicy(sizePolicy);
        tBtn_TCPXPosAdd->setCheckable(false);
        tBtn_TCPXPosAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPXPosAdd->setAutoRaise(false);
        tBtn_TCPXPosAdd->setArrowType(Qt::RightArrow);
        tBtn_TCPZPosAdd = new QToolButton(centralwidget);
        tBtn_TCPZPosAdd->setObjectName(QString::fromUtf8("tBtn_TCPZPosAdd"));
        tBtn_TCPZPosAdd->setGeometry(QRect(1060, 80, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPZPosAdd->sizePolicy().hasHeightForWidth());
        tBtn_TCPZPosAdd->setSizePolicy(sizePolicy);
        tBtn_TCPZPosAdd->setCheckable(false);
        tBtn_TCPZPosAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPZPosAdd->setAutoRaise(false);
        tBtn_TCPZPosAdd->setArrowType(Qt::UpArrow);
        tBtn_TCPYPosAdd = new QToolButton(centralwidget);
        tBtn_TCPYPosAdd->setObjectName(QString::fromUtf8("tBtn_TCPYPosAdd"));
        tBtn_TCPYPosAdd->setGeometry(QRect(1010, 140, 51, 71));
        sizePolicy.setHeightForWidth(tBtn_TCPYPosAdd->sizePolicy().hasHeightForWidth());
        tBtn_TCPYPosAdd->setSizePolicy(sizePolicy);
        tBtn_TCPYPosAdd->setCheckable(false);
        tBtn_TCPYPosAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPYPosAdd->setAutoRaise(false);
        tBtn_TCPYPosAdd->setArrowType(Qt::UpArrow);
        tBtn_TCPXPosDec = new QToolButton(centralwidget);
        tBtn_TCPXPosDec->setObjectName(QString::fromUtf8("tBtn_TCPXPosDec"));
        tBtn_TCPXPosDec->setGeometry(QRect(880, 200, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPXPosDec->sizePolicy().hasHeightForWidth());
        tBtn_TCPXPosDec->setSizePolicy(sizePolicy);
        tBtn_TCPXPosDec->setCheckable(false);
        tBtn_TCPXPosDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPXPosDec->setAutoRaise(false);
        tBtn_TCPXPosDec->setArrowType(Qt::LeftArrow);
        tBtn_TCPZPosDec = new QToolButton(centralwidget);
        tBtn_TCPZPosDec->setObjectName(QString::fromUtf8("tBtn_TCPZPosDec"));
        tBtn_TCPZPosDec->setGeometry(QRect(920, 80, 101, 51));
        sizePolicy.setHeightForWidth(tBtn_TCPZPosDec->sizePolicy().hasHeightForWidth());
        tBtn_TCPZPosDec->setSizePolicy(sizePolicy);
        tBtn_TCPZPosDec->setCheckable(false);
        tBtn_TCPZPosDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPZPosDec->setAutoRaise(false);
        tBtn_TCPZPosDec->setArrowType(Qt::DownArrow);
        tBtn_TCPYPosDec = new QToolButton(centralwidget);
        tBtn_TCPYPosDec->setObjectName(QString::fromUtf8("tBtn_TCPYPosDec"));
        tBtn_TCPYPosDec->setGeometry(QRect(1010, 240, 51, 71));
        sizePolicy.setHeightForWidth(tBtn_TCPYPosDec->sizePolicy().hasHeightForWidth());
        tBtn_TCPYPosDec->setSizePolicy(sizePolicy);
        tBtn_TCPYPosDec->setCheckable(false);
        tBtn_TCPYPosDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_TCPYPosDec->setAutoRaise(false);
        tBtn_TCPYPosDec->setArrowType(Qt::DownArrow);
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(430, 90, 51, 24));
        label->setFont(font);
        label->setAlignment(Qt::AlignCenter);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(720, 90, 51, 24));
        label_2->setFont(font);
        label_2->setAlignment(Qt::AlignCenter);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(390, 210, 51, 24));
        label_3->setFont(font1);
        label_3->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(750, 210, 51, 24));
        label_4->setFont(font1);
        label_4->setAlignment(Qt::AlignCenter);
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(580, 110, 41, 24));
        label_5->setFont(font1);
        label_5->setAlignment(Qt::AlignCenter);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(580, 310, 31, 24));
        label_6->setFont(font1);
        label_6->setAlignment(Qt::AlignCenter);
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(830, 210, 51, 24));
        label_7->setFont(font1);
        label_7->setAlignment(Qt::AlignCenter);
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(1190, 210, 51, 24));
        label_8->setFont(font1);
        label_8->setAlignment(Qt::AlignCenter);
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(1020, 310, 31, 24));
        label_9->setFont(font1);
        label_9->setAlignment(Qt::AlignCenter);
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(1020, 110, 31, 24));
        label_10->setFont(font1);
        label_10->setAlignment(Qt::AlignCenter);
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(1170, 90, 31, 24));
        label_11->setFont(font1);
        label_11->setAlignment(Qt::AlignCenter);
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(880, 90, 31, 24));
        label_12->setFont(font1);
        label_12->setAlignment(Qt::AlignCenter);
        Slider_Base = new QSlider(centralwidget);
        Slider_Base->setObjectName(QString::fromUtf8("Slider_Base"));
        Slider_Base->setGeometry(QRect(540, 400, 501, 22));
        sizePolicy.setHeightForWidth(Slider_Base->sizePolicy().hasHeightForWidth());
        Slider_Base->setSizePolicy(sizePolicy);
        Slider_Base->setMinimum(-360);
        Slider_Base->setMaximum(360);
        Slider_Base->setOrientation(Qt::Horizontal);
        Slider_Base->setTickPosition(QSlider::TicksAbove);
        Slider_Base->setTickInterval(90);
        tabWidget = new QTabWidget(centralwidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(40, 390, 321, 301));
        sizePolicy.setHeightForWidth(tabWidget->sizePolicy().hasHeightForWidth());
        tabWidget->setSizePolicy(sizePolicy);
        tabWidget->setFont(font1);
        tab_current = new QWidget();
        tab_current->setObjectName(QString::fromUtf8("tab_current"));
        lineEdit_X = new QLineEdit(tab_current);
        lineEdit_X->setObjectName(QString::fromUtf8("lineEdit_X"));
        lineEdit_X->setGeometry(QRect(80, 20, 141, 30));
        lineEdit_X->setAlignment(Qt::AlignCenter);
        lineEdit_X->setReadOnly(true);
        lineEdit_Y = new QLineEdit(tab_current);
        lineEdit_Y->setObjectName(QString::fromUtf8("lineEdit_Y"));
        lineEdit_Y->setGeometry(QRect(80, 60, 141, 30));
        lineEdit_Y->setAlignment(Qt::AlignCenter);
        lineEdit_Y->setReadOnly(true);
        lineEdit_RX = new QLineEdit(tab_current);
        lineEdit_RX->setObjectName(QString::fromUtf8("lineEdit_RX"));
        lineEdit_RX->setGeometry(QRect(80, 140, 141, 30));
        lineEdit_RX->setAlignment(Qt::AlignCenter);
        lineEdit_RX->setReadOnly(true);
        lineEdit_Z = new QLineEdit(tab_current);
        lineEdit_Z->setObjectName(QString::fromUtf8("lineEdit_Z"));
        lineEdit_Z->setGeometry(QRect(80, 100, 141, 30));
        lineEdit_Z->setAlignment(Qt::AlignCenter);
        lineEdit_Z->setReadOnly(true);
        lineEdit_RZ = new QLineEdit(tab_current);
        lineEdit_RZ->setObjectName(QString::fromUtf8("lineEdit_RZ"));
        lineEdit_RZ->setGeometry(QRect(80, 220, 141, 30));
        lineEdit_RZ->setAlignment(Qt::AlignCenter);
        lineEdit_RZ->setReadOnly(true);
        lineEdit_RY = new QLineEdit(tab_current);
        lineEdit_RY->setObjectName(QString::fromUtf8("lineEdit_RY"));
        lineEdit_RY->setGeometry(QRect(80, 180, 141, 30));
        lineEdit_RY->setAlignment(Qt::AlignCenter);
        lineEdit_RY->setReadOnly(true);
        label_19 = new QLabel(tab_current);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(40, 20, 31, 24));
        label_19->setFont(font1);
        label_19->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_20 = new QLabel(tab_current);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(40, 60, 31, 24));
        label_20->setFont(font1);
        label_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_21 = new QLabel(tab_current);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(40, 100, 31, 24));
        label_21->setFont(font1);
        label_21->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(tab_current);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(40, 140, 31, 24));
        label_22->setFont(font1);
        label_22->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_23 = new QLabel(tab_current);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(40, 180, 31, 24));
        label_23->setFont(font1);
        label_23->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_24 = new QLabel(tab_current);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(40, 220, 31, 24));
        label_24->setFont(font1);
        label_24->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_25 = new QLabel(tab_current);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(220, 20, 51, 24));
        label_25->setFont(font1);
        label_25->setAlignment(Qt::AlignCenter);
        label_26 = new QLabel(tab_current);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(220, 60, 51, 24));
        label_26->setFont(font1);
        label_26->setAlignment(Qt::AlignCenter);
        label_27 = new QLabel(tab_current);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(220, 100, 51, 24));
        label_27->setFont(font1);
        label_27->setAlignment(Qt::AlignCenter);
        label_28 = new QLabel(tab_current);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(220, 140, 51, 24));
        label_28->setFont(font1);
        label_28->setAlignment(Qt::AlignCenter);
        label_29 = new QLabel(tab_current);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(220, 180, 51, 24));
        label_29->setFont(font1);
        label_29->setAlignment(Qt::AlignCenter);
        label_30 = new QLabel(tab_current);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(220, 220, 51, 24));
        label_30->setFont(font1);
        label_30->setAlignment(Qt::AlignCenter);
        tabWidget->addTab(tab_current, QString());
        tab_target = new QWidget();
        tab_target->setObjectName(QString::fromUtf8("tab_target"));
        label_31 = new QLabel(tab_target);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(40, 100, 31, 24));
        label_31->setFont(font1);
        label_31->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_32 = new QLabel(tab_target);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(40, 20, 31, 24));
        label_32->setFont(font1);
        label_32->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_33 = new QLabel(tab_target);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(220, 220, 51, 24));
        label_33->setFont(font1);
        label_33->setAlignment(Qt::AlignCenter);
        lineEdit_Z_target = new QLineEdit(tab_target);
        lineEdit_Z_target->setObjectName(QString::fromUtf8("lineEdit_Z_target"));
        lineEdit_Z_target->setGeometry(QRect(80, 100, 141, 30));
        lineEdit_Z_target->setAlignment(Qt::AlignCenter);
        lineEdit_Z_target->setReadOnly(false);
        label_34 = new QLabel(tab_target);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(40, 220, 31, 24));
        label_34->setFont(font1);
        label_34->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_Y_target = new QLineEdit(tab_target);
        lineEdit_Y_target->setObjectName(QString::fromUtf8("lineEdit_Y_target"));
        lineEdit_Y_target->setGeometry(QRect(80, 60, 141, 30));
        lineEdit_Y_target->setAlignment(Qt::AlignCenter);
        lineEdit_Y_target->setReadOnly(false);
        label_35 = new QLabel(tab_target);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(220, 100, 51, 24));
        label_35->setFont(font1);
        label_35->setAlignment(Qt::AlignCenter);
        label_36 = new QLabel(tab_target);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(40, 60, 31, 24));
        label_36->setFont(font1);
        label_36->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_X_target = new QLineEdit(tab_target);
        lineEdit_X_target->setObjectName(QString::fromUtf8("lineEdit_X_target"));
        lineEdit_X_target->setGeometry(QRect(80, 20, 141, 30));
        lineEdit_X_target->setAlignment(Qt::AlignCenter);
        lineEdit_X_target->setReadOnly(false);
        label_37 = new QLabel(tab_target);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(40, 180, 31, 24));
        label_37->setFont(font1);
        label_37->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_38 = new QLabel(tab_target);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(40, 140, 31, 24));
        label_38->setFont(font1);
        label_38->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_39 = new QLabel(tab_target);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(220, 20, 51, 24));
        label_39->setFont(font1);
        label_39->setAlignment(Qt::AlignCenter);
        lineEdit_RZ_target = new QLineEdit(tab_target);
        lineEdit_RZ_target->setObjectName(QString::fromUtf8("lineEdit_RZ_target"));
        lineEdit_RZ_target->setGeometry(QRect(80, 220, 141, 30));
        lineEdit_RZ_target->setAlignment(Qt::AlignCenter);
        lineEdit_RZ_target->setReadOnly(false);
        lineEdit_RX_target = new QLineEdit(tab_target);
        lineEdit_RX_target->setObjectName(QString::fromUtf8("lineEdit_RX_target"));
        lineEdit_RX_target->setGeometry(QRect(80, 140, 141, 30));
        lineEdit_RX_target->setAlignment(Qt::AlignCenter);
        lineEdit_RX_target->setReadOnly(false);
        label_40 = new QLabel(tab_target);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(220, 60, 51, 24));
        label_40->setFont(font1);
        label_40->setAlignment(Qt::AlignCenter);
        label_41 = new QLabel(tab_target);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(220, 140, 51, 24));
        label_41->setFont(font1);
        label_41->setAlignment(Qt::AlignCenter);
        label_42 = new QLabel(tab_target);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(220, 180, 51, 24));
        label_42->setFont(font1);
        label_42->setAlignment(Qt::AlignCenter);
        lineEdit_RY_target = new QLineEdit(tab_target);
        lineEdit_RY_target->setObjectName(QString::fromUtf8("lineEdit_RY_target"));
        lineEdit_RY_target->setGeometry(QRect(80, 180, 141, 30));
        lineEdit_RY_target->setAlignment(Qt::AlignCenter);
        lineEdit_RY_target->setReadOnly(false);
        tabWidget->addTab(tab_target, QString());
        tBtn_URBaseDec = new QToolButton(centralwidget);
        tBtn_URBaseDec->setObjectName(QString::fromUtf8("tBtn_URBaseDec"));
        tBtn_URBaseDec->setGeometry(QRect(450, 400, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URBaseDec->sizePolicy().hasHeightForWidth());
        tBtn_URBaseDec->setSizePolicy(sizePolicy);
        tBtn_URBaseDec->setCheckable(false);
        tBtn_URBaseDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URBaseDec->setAutoRaise(false);
        tBtn_URBaseDec->setArrowType(Qt::LeftArrow);
        tBtn_URBaseAdd = new QToolButton(centralwidget);
        tBtn_URBaseAdd->setObjectName(QString::fromUtf8("tBtn_URBaseAdd"));
        tBtn_URBaseAdd->setGeometry(QRect(1060, 400, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URBaseAdd->sizePolicy().hasHeightForWidth());
        tBtn_URBaseAdd->setSizePolicy(sizePolicy);
        tBtn_URBaseAdd->setCheckable(false);
        tBtn_URBaseAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URBaseAdd->setAutoRaise(false);
        tBtn_URBaseAdd->setArrowType(Qt::RightArrow);
        lineEdit_base = new QLineEdit(centralwidget);
        lineEdit_base->setObjectName(QString::fromUtf8("lineEdit_base"));
        lineEdit_base->setGeometry(QRect(1140, 400, 71, 21));
        sizePolicy.setHeightForWidth(lineEdit_base->sizePolicy().hasHeightForWidth());
        lineEdit_base->setSizePolicy(sizePolicy);
        lineEdit_base->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_base->setReadOnly(true);
        lineEdit_base->setClearButtonEnabled(false);
        label_base = new QLabel(centralwidget);
        label_base->setObjectName(QString::fromUtf8("label_base"));
        label_base->setGeometry(QRect(390, 400, 61, 24));
        label_base->setFont(font);
        label_base->setLineWidth(1);
        label_base->setAlignment(Qt::AlignCenter);
        tBtn_URShoulderAdd = new QToolButton(centralwidget);
        tBtn_URShoulderAdd->setObjectName(QString::fromUtf8("tBtn_URShoulderAdd"));
        tBtn_URShoulderAdd->setGeometry(QRect(1060, 450, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URShoulderAdd->sizePolicy().hasHeightForWidth());
        tBtn_URShoulderAdd->setSizePolicy(sizePolicy);
        tBtn_URShoulderAdd->setCheckable(false);
        tBtn_URShoulderAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URShoulderAdd->setAutoRaise(false);
        tBtn_URShoulderAdd->setArrowType(Qt::RightArrow);
        lineEdit_shoulder = new QLineEdit(centralwidget);
        lineEdit_shoulder->setObjectName(QString::fromUtf8("lineEdit_shoulder"));
        lineEdit_shoulder->setGeometry(QRect(1140, 450, 71, 21));
        sizePolicy.setHeightForWidth(lineEdit_shoulder->sizePolicy().hasHeightForWidth());
        lineEdit_shoulder->setSizePolicy(sizePolicy);
        lineEdit_shoulder->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_shoulder->setReadOnly(true);
        label_shoulder = new QLabel(centralwidget);
        label_shoulder->setObjectName(QString::fromUtf8("label_shoulder"));
        label_shoulder->setGeometry(QRect(390, 450, 61, 24));
        label_shoulder->setFont(font);
        label_shoulder->setLineWidth(1);
        label_shoulder->setAlignment(Qt::AlignCenter);
        Slider_Shoulder = new QSlider(centralwidget);
        Slider_Shoulder->setObjectName(QString::fromUtf8("Slider_Shoulder"));
        Slider_Shoulder->setGeometry(QRect(540, 450, 501, 22));
        sizePolicy.setHeightForWidth(Slider_Shoulder->sizePolicy().hasHeightForWidth());
        Slider_Shoulder->setSizePolicy(sizePolicy);
        Slider_Shoulder->setMinimum(-360);
        Slider_Shoulder->setMaximum(360);
        Slider_Shoulder->setOrientation(Qt::Horizontal);
        Slider_Shoulder->setTickPosition(QSlider::TicksAbove);
        Slider_Shoulder->setTickInterval(90);
        tBtn_URShoulderDec = new QToolButton(centralwidget);
        tBtn_URShoulderDec->setObjectName(QString::fromUtf8("tBtn_URShoulderDec"));
        tBtn_URShoulderDec->setGeometry(QRect(450, 450, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URShoulderDec->sizePolicy().hasHeightForWidth());
        tBtn_URShoulderDec->setSizePolicy(sizePolicy);
        tBtn_URShoulderDec->setCheckable(false);
        tBtn_URShoulderDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URShoulderDec->setAutoRaise(false);
        tBtn_URShoulderDec->setArrowType(Qt::LeftArrow);
        tBtn_URElbowAdd = new QToolButton(centralwidget);
        tBtn_URElbowAdd->setObjectName(QString::fromUtf8("tBtn_URElbowAdd"));
        tBtn_URElbowAdd->setGeometry(QRect(1060, 500, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URElbowAdd->sizePolicy().hasHeightForWidth());
        tBtn_URElbowAdd->setSizePolicy(sizePolicy);
        tBtn_URElbowAdd->setCheckable(false);
        tBtn_URElbowAdd->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URElbowAdd->setAutoRaise(false);
        tBtn_URElbowAdd->setArrowType(Qt::RightArrow);
        lineEdit_elbow = new QLineEdit(centralwidget);
        lineEdit_elbow->setObjectName(QString::fromUtf8("lineEdit_elbow"));
        lineEdit_elbow->setGeometry(QRect(1140, 500, 71, 21));
        sizePolicy.setHeightForWidth(lineEdit_elbow->sizePolicy().hasHeightForWidth());
        lineEdit_elbow->setSizePolicy(sizePolicy);
        lineEdit_elbow->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_elbow->setReadOnly(true);
        label_elbow = new QLabel(centralwidget);
        label_elbow->setObjectName(QString::fromUtf8("label_elbow"));
        label_elbow->setGeometry(QRect(390, 500, 61, 24));
        label_elbow->setFont(font);
        label_elbow->setLineWidth(1);
        label_elbow->setAlignment(Qt::AlignCenter);
        Slider_Elbow = new QSlider(centralwidget);
        Slider_Elbow->setObjectName(QString::fromUtf8("Slider_Elbow"));
        Slider_Elbow->setGeometry(QRect(540, 500, 501, 22));
        sizePolicy.setHeightForWidth(Slider_Elbow->sizePolicy().hasHeightForWidth());
        Slider_Elbow->setSizePolicy(sizePolicy);
        Slider_Elbow->setMinimum(-360);
        Slider_Elbow->setMaximum(360);
        Slider_Elbow->setOrientation(Qt::Horizontal);
        Slider_Elbow->setTickPosition(QSlider::TicksAbove);
        Slider_Elbow->setTickInterval(90);
        tBtn_URElbowDec = new QToolButton(centralwidget);
        tBtn_URElbowDec->setObjectName(QString::fromUtf8("tBtn_URElbowDec"));
        tBtn_URElbowDec->setGeometry(QRect(450, 500, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URElbowDec->sizePolicy().hasHeightForWidth());
        tBtn_URElbowDec->setSizePolicy(sizePolicy);
        tBtn_URElbowDec->setCheckable(false);
        tBtn_URElbowDec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URElbowDec->setAutoRaise(false);
        tBtn_URElbowDec->setArrowType(Qt::LeftArrow);
        tBtn_URWrist1Add = new QToolButton(centralwidget);
        tBtn_URWrist1Add->setObjectName(QString::fromUtf8("tBtn_URWrist1Add"));
        tBtn_URWrist1Add->setGeometry(QRect(1060, 540, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URWrist1Add->sizePolicy().hasHeightForWidth());
        tBtn_URWrist1Add->setSizePolicy(sizePolicy);
        tBtn_URWrist1Add->setCheckable(false);
        tBtn_URWrist1Add->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URWrist1Add->setAutoRaise(false);
        tBtn_URWrist1Add->setArrowType(Qt::RightArrow);
        tBtn_URWrist2Add = new QToolButton(centralwidget);
        tBtn_URWrist2Add->setObjectName(QString::fromUtf8("tBtn_URWrist2Add"));
        tBtn_URWrist2Add->setGeometry(QRect(1060, 590, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URWrist2Add->sizePolicy().hasHeightForWidth());
        tBtn_URWrist2Add->setSizePolicy(sizePolicy);
        tBtn_URWrist2Add->setCheckable(false);
        tBtn_URWrist2Add->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URWrist2Add->setAutoRaise(false);
        tBtn_URWrist2Add->setArrowType(Qt::RightArrow);
        Slider_Wrist2 = new QSlider(centralwidget);
        Slider_Wrist2->setObjectName(QString::fromUtf8("Slider_Wrist2"));
        Slider_Wrist2->setGeometry(QRect(540, 590, 501, 22));
        sizePolicy.setHeightForWidth(Slider_Wrist2->sizePolicy().hasHeightForWidth());
        Slider_Wrist2->setSizePolicy(sizePolicy);
        Slider_Wrist2->setMinimum(-360);
        Slider_Wrist2->setMaximum(360);
        Slider_Wrist2->setOrientation(Qt::Horizontal);
        Slider_Wrist2->setTickPosition(QSlider::TicksAbove);
        Slider_Wrist2->setTickInterval(90);
        tBtn_URWrist3Add = new QToolButton(centralwidget);
        tBtn_URWrist3Add->setObjectName(QString::fromUtf8("tBtn_URWrist3Add"));
        tBtn_URWrist3Add->setGeometry(QRect(1060, 640, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URWrist3Add->sizePolicy().hasHeightForWidth());
        tBtn_URWrist3Add->setSizePolicy(sizePolicy);
        tBtn_URWrist3Add->setCheckable(false);
        tBtn_URWrist3Add->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URWrist3Add->setAutoRaise(false);
        tBtn_URWrist3Add->setArrowType(Qt::RightArrow);
        tBtn_URWrist3Dec = new QToolButton(centralwidget);
        tBtn_URWrist3Dec->setObjectName(QString::fromUtf8("tBtn_URWrist3Dec"));
        tBtn_URWrist3Dec->setGeometry(QRect(450, 640, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URWrist3Dec->sizePolicy().hasHeightForWidth());
        tBtn_URWrist3Dec->setSizePolicy(sizePolicy);
        tBtn_URWrist3Dec->setCheckable(false);
        tBtn_URWrist3Dec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URWrist3Dec->setAutoRaise(false);
        tBtn_URWrist3Dec->setArrowType(Qt::LeftArrow);
        label_wrist3 = new QLabel(centralwidget);
        label_wrist3->setObjectName(QString::fromUtf8("label_wrist3"));
        label_wrist3->setGeometry(QRect(390, 640, 61, 24));
        label_wrist3->setFont(font);
        label_wrist3->setLineWidth(1);
        label_wrist3->setAlignment(Qt::AlignCenter);
        lineEdit_wrist1 = new QLineEdit(centralwidget);
        lineEdit_wrist1->setObjectName(QString::fromUtf8("lineEdit_wrist1"));
        lineEdit_wrist1->setGeometry(QRect(1140, 540, 71, 21));
        sizePolicy.setHeightForWidth(lineEdit_wrist1->sizePolicy().hasHeightForWidth());
        lineEdit_wrist1->setSizePolicy(sizePolicy);
        lineEdit_wrist1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_wrist1->setReadOnly(true);
        label_wrist2 = new QLabel(centralwidget);
        label_wrist2->setObjectName(QString::fromUtf8("label_wrist2"));
        label_wrist2->setGeometry(QRect(390, 590, 61, 24));
        label_wrist2->setFont(font);
        label_wrist2->setLineWidth(1);
        label_wrist2->setAlignment(Qt::AlignCenter);
        tBtn_URWrist2Dec = new QToolButton(centralwidget);
        tBtn_URWrist2Dec->setObjectName(QString::fromUtf8("tBtn_URWrist2Dec"));
        tBtn_URWrist2Dec->setGeometry(QRect(450, 590, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URWrist2Dec->sizePolicy().hasHeightForWidth());
        tBtn_URWrist2Dec->setSizePolicy(sizePolicy);
        tBtn_URWrist2Dec->setCheckable(false);
        tBtn_URWrist2Dec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URWrist2Dec->setAutoRaise(false);
        tBtn_URWrist2Dec->setArrowType(Qt::LeftArrow);
        lineEdit_wrist3 = new QLineEdit(centralwidget);
        lineEdit_wrist3->setObjectName(QString::fromUtf8("lineEdit_wrist3"));
        lineEdit_wrist3->setGeometry(QRect(1140, 640, 71, 21));
        sizePolicy.setHeightForWidth(lineEdit_wrist3->sizePolicy().hasHeightForWidth());
        lineEdit_wrist3->setSizePolicy(sizePolicy);
        lineEdit_wrist3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_wrist3->setReadOnly(true);
        label_wrist1 = new QLabel(centralwidget);
        label_wrist1->setObjectName(QString::fromUtf8("label_wrist1"));
        label_wrist1->setGeometry(QRect(390, 540, 61, 24));
        label_wrist1->setFont(font);
        label_wrist1->setLineWidth(1);
        label_wrist1->setAlignment(Qt::AlignCenter);
        lineEdit_wrist2 = new QLineEdit(centralwidget);
        lineEdit_wrist2->setObjectName(QString::fromUtf8("lineEdit_wrist2"));
        lineEdit_wrist2->setGeometry(QRect(1140, 590, 71, 21));
        sizePolicy.setHeightForWidth(lineEdit_wrist2->sizePolicy().hasHeightForWidth());
        lineEdit_wrist2->setSizePolicy(sizePolicy);
        lineEdit_wrist2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_wrist2->setReadOnly(true);
        Slider_Wrist1 = new QSlider(centralwidget);
        Slider_Wrist1->setObjectName(QString::fromUtf8("Slider_Wrist1"));
        Slider_Wrist1->setGeometry(QRect(540, 540, 501, 22));
        sizePolicy.setHeightForWidth(Slider_Wrist1->sizePolicy().hasHeightForWidth());
        Slider_Wrist1->setSizePolicy(sizePolicy);
        Slider_Wrist1->setMinimum(-360);
        Slider_Wrist1->setMaximum(360);
        Slider_Wrist1->setOrientation(Qt::Horizontal);
        Slider_Wrist1->setTickPosition(QSlider::TicksAbove);
        Slider_Wrist1->setTickInterval(90);
        tBtn_URWrist1Dec = new QToolButton(centralwidget);
        tBtn_URWrist1Dec->setObjectName(QString::fromUtf8("tBtn_URWrist1Dec"));
        tBtn_URWrist1Dec->setGeometry(QRect(450, 540, 71, 21));
        sizePolicy.setHeightForWidth(tBtn_URWrist1Dec->sizePolicy().hasHeightForWidth());
        tBtn_URWrist1Dec->setSizePolicy(sizePolicy);
        tBtn_URWrist1Dec->setCheckable(false);
        tBtn_URWrist1Dec->setPopupMode(QToolButton::DelayedPopup);
        tBtn_URWrist1Dec->setAutoRaise(false);
        tBtn_URWrist1Dec->setArrowType(Qt::LeftArrow);
        Slider_Wrist3 = new QSlider(centralwidget);
        Slider_Wrist3->setObjectName(QString::fromUtf8("Slider_Wrist3"));
        Slider_Wrist3->setGeometry(QRect(540, 640, 501, 22));
        sizePolicy.setHeightForWidth(Slider_Wrist3->sizePolicy().hasHeightForWidth());
        Slider_Wrist3->setSizePolicy(sizePolicy);
        Slider_Wrist3->setMinimum(-360);
        Slider_Wrist3->setMaximum(360);
        Slider_Wrist3->setSliderPosition(0);
        Slider_Wrist3->setOrientation(Qt::Horizontal);
        Slider_Wrist3->setTickPosition(QSlider::TicksAbove);
        Slider_Wrist3->setTickInterval(90);
        label_TCPDirection_2 = new QLabel(centralwidget);
        label_TCPDirection_2->setObjectName(QString::fromUtf8("label_TCPDirection_2"));
        label_TCPDirection_2->setGeometry(QRect(400, 350, 181, 24));
        label_TCPDirection_2->setFont(font);
        label_TCPDirection_3 = new QLabel(centralwidget);
        label_TCPDirection_3->setObjectName(QString::fromUtf8("label_TCPDirection_3"));
        label_TCPDirection_3->setGeometry(QRect(40, 350, 161, 24));
        label_TCPDirection_3->setFont(font1);
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(1210, 400, 31, 24));
        label_13->setFont(font1);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(1210, 450, 31, 24));
        label_14->setFont(font1);
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(1210, 500, 31, 24));
        label_15->setFont(font1);
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(1210, 540, 31, 24));
        label_16->setFont(font1);
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(1210, 590, 31, 24));
        label_17->setFont(font1);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(1210, 640, 31, 24));
        label_18->setFont(font1);
        pBtn_MoveTo = new QPushButton(centralwidget);
        pBtn_MoveTo->setObjectName(QString::fromUtf8("pBtn_MoveTo"));
        pBtn_MoveTo->setGeometry(QRect(210, 350, 151, 33));
        MainWindow->setCentralWidget(centralwidget);
        line_10->raise();
        line_9->raise();
        line_5->raise();
        line_7->raise();
        line_6->raise();
        widget_RTClient->raise();
        line->raise();
        line_2->raise();
        line_3->raise();
        line_4->raise();
        widget_DashBoard->raise();
        widget->raise();
        tBtn_TCPZDirDec->raise();
        label_TCPDirection->raise();
        label_TCPPostion->raise();
        tBtn_TCPZDirAdd->raise();
        tBtn_TCPYDirAdd->raise();
        tBtn_TCPYDirDec->raise();
        tBtn_TCPXDirDec->raise();
        tBtn_TCPXDirAdd->raise();
        tBtn_TCPXPosAdd->raise();
        tBtn_TCPZPosAdd->raise();
        tBtn_TCPYPosAdd->raise();
        tBtn_TCPXPosDec->raise();
        tBtn_TCPZPosDec->raise();
        tBtn_TCPYPosDec->raise();
        label->raise();
        label_2->raise();
        label_3->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        Slider_Base->raise();
        tabWidget->raise();
        tBtn_URBaseDec->raise();
        tBtn_URBaseAdd->raise();
        lineEdit_base->raise();
        label_base->raise();
        tBtn_URShoulderAdd->raise();
        lineEdit_shoulder->raise();
        label_shoulder->raise();
        Slider_Shoulder->raise();
        tBtn_URShoulderDec->raise();
        tBtn_URElbowAdd->raise();
        lineEdit_elbow->raise();
        label_elbow->raise();
        Slider_Elbow->raise();
        tBtn_URElbowDec->raise();
        tBtn_URWrist1Add->raise();
        tBtn_URWrist2Add->raise();
        Slider_Wrist2->raise();
        tBtn_URWrist3Add->raise();
        tBtn_URWrist3Dec->raise();
        label_wrist3->raise();
        lineEdit_wrist1->raise();
        label_wrist2->raise();
        tBtn_URWrist2Dec->raise();
        lineEdit_wrist3->raise();
        label_wrist1->raise();
        lineEdit_wrist2->raise();
        Slider_Wrist1->raise();
        tBtn_URWrist1Dec->raise();
        Slider_Wrist3->raise();
        label_TCPDirection_2->raise();
        label_TCPDirection_3->raise();
        label_13->raise();
        label_14->raise();
        label_15->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        pBtn_MoveTo->raise();

        retranslateUi(MainWindow);

        tabWidget->setCurrentIndex(1);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "UR\346\234\272\346\242\260\350\207\202\346\216\247\345\210\266(dzc)", nullptr));
        label_RTClient->setText(QCoreApplication::translate("MainWindow", "RTClient", nullptr));
        pBtn_ConnectUR->setText(QCoreApplication::translate("MainWindow", "\350\277\236\346\216\245", nullptr));
        lineEdt_IPAdress->setText(QCoreApplication::translate("MainWindow", "192.168.1.11", nullptr));
        pBtn_DisconnectUR->setText(QCoreApplication::translate("MainWindow", "\346\226\255\345\274\200", nullptr));
        pBtn_Powerdown->setText(QCoreApplication::translate("MainWindow", "\346\226\255\347\224\265", nullptr));
        pBtn_BreakRelease->setText(QCoreApplication::translate("MainWindow", "\350\247\243\351\231\244\345\210\271\350\275\246", nullptr));
        pBtn_Poweron->setText(QCoreApplication::translate("MainWindow", "\344\270\212\347\224\265", nullptr));
        pBtn_Poweroff->setText(QCoreApplication::translate("MainWindow", "\344\270\213\347\224\265", nullptr));
        label_DashBoard->setText(QCoreApplication::translate("MainWindow", "DashBoard", nullptr));
        pBtn_StopJoint->setText(QCoreApplication::translate("MainWindow", "\345\201\234\346\255\242\345\205\263\350\212\202", nullptr));
        pBtn_BackStart->setText(QCoreApplication::translate("MainWindow", "\345\275\222\344\275\215", nullptr));
        pBtn_BackZero->setText(QCoreApplication::translate("MainWindow", "\345\233\236\351\233\266", nullptr));
        tBtn_TCPZDirDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_TCPDirection->setText(QCoreApplication::translate("MainWindow", "TCP\346\226\271\345\220\221\350\260\203\346\225\264", nullptr));
        label_TCPPostion->setText(QCoreApplication::translate("MainWindow", "TCP\344\275\215\347\275\256\350\260\203\346\225\264", nullptr));
        tBtn_TCPZDirAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPYDirAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPYDirDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPXDirDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPXDirAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPXPosAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPZPosAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPYPosAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPXPosDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPZPosDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_TCPYPosDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264\342\206\223", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264\342\206\221", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Y+", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Y-", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "X-", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "X+", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Y-", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Y+", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Z\342\206\221", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Z\342\206\223", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindow", "RX", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindow", "RY", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindow", "RZ", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindow", "mm", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindow", "mm", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindow", "mm", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindow", "rad", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindow", "rad", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindow", "rad", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_current), QCoreApplication::translate("MainWindow", "\345\275\223\345\211\215\345\247\277\346\200\201", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindow", "Z", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindow", "X", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "rad", nullptr));
        lineEdit_Z_target->setText(QCoreApplication::translate("MainWindow", "31.86", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "RZ", nullptr));
        lineEdit_Y_target->setText(QCoreApplication::translate("MainWindow", "-486.90", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "mm", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindow", "Y", nullptr));
        lineEdit_X_target->setText(QCoreApplication::translate("MainWindow", "109.15", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "RY", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "RX", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindow", "mm", nullptr));
        lineEdit_RZ_target->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        lineEdit_RX_target->setText(QCoreApplication::translate("MainWindow", "0", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindow", "mm", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindow", "rad", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "rad", nullptr));
        lineEdit_RY_target->setText(QCoreApplication::translate("MainWindow", "3.1416", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_target), QCoreApplication::translate("MainWindow", "\347\233\256\346\240\207\345\247\277\346\200\201", nullptr));
        tBtn_URBaseDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_URBaseAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_base->setText(QCoreApplication::translate("MainWindow", "\345\237\272\345\272\247", nullptr));
        tBtn_URShoulderAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_shoulder->setText(QCoreApplication::translate("MainWindow", "\350\202\251\351\203\250", nullptr));
        tBtn_URShoulderDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_URElbowAdd->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_elbow->setText(QCoreApplication::translate("MainWindow", "\350\202\230\351\203\250", nullptr));
        tBtn_URElbowDec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_URWrist1Add->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_URWrist2Add->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_URWrist3Add->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        tBtn_URWrist3Dec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_wrist3->setText(QCoreApplication::translate("MainWindow", "\346\211\213\350\205\2253", nullptr));
        label_wrist2->setText(QCoreApplication::translate("MainWindow", "\346\211\213\350\205\2252", nullptr));
        tBtn_URWrist2Dec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_wrist1->setText(QCoreApplication::translate("MainWindow", "\346\211\213\350\205\2251", nullptr));
        tBtn_URWrist1Dec->setText(QCoreApplication::translate("MainWindow", "Z\350\275\264", nullptr));
        label_TCPDirection_2->setText(QCoreApplication::translate("MainWindow", "\346\234\272\346\242\260\350\207\202\345\205\255\350\275\264\347\232\204\345\215\225\347\213\254\346\216\247\345\210\266", nullptr));
        label_TCPDirection_3->setText(QCoreApplication::translate("MainWindow", "TCP\345\235\220\346\240\207\346\230\276\347\244\272\344\270\216\347\274\226\350\276\221", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "\302\260", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "\302\260", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "\302\260", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindow", "\302\260", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindow", "\302\260", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindow", "\302\260", nullptr));
        pBtn_MoveTo->setText(QCoreApplication::translate("MainWindow", "\347\247\273\345\212\250\345\210\260\346\214\207\345\256\232\344\275\215\347\275\256", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
